# Generated by Django 5.2.3 on 2025-09-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_localidad_pais_usuario_calle_usuario_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Paises'},
        ),
        migrations.AddField(
            model_name='localidad',
            name='slug',
            field=models.SlugField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='provincia',
            name='georef_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='provincia',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tyc_aceptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tyc_aceptado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tyc_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='nombre',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
