# Generated by Django 5.2.3 on 2025-10-27 21:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_pais_options_localidad_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Exchange', max_length=50, unique=True)),
                ('saldo_ars', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_usdt', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('saldo_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='margin_bps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ref_compra',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ref_venta',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_confirm_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ApunteExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('comision_swap', 'Comisión SWAP'), ('spread_compra', 'Spread en COMPRA'), ('spread_venta', 'Spread en VENTA'), ('ajuste', 'Ajuste contable'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='ingreso', max_length=30)),
                ('categoria', models.CharField(choices=[('spread_compra', 'Spread en COMPRA'), ('spread_venta', 'Spread en VENTA'), ('fee_swap', 'Comisión de SWAP'), ('entrada', 'Entrada (depósito acreditado)'), ('salida', 'Salida (retiro enviado)'), ('ajuste', 'Ajuste contable')], default='ajuste', max_length=40)),
                ('moneda', models.CharField(choices=[('ARS', 'ARS'), ('USDT', 'USDT'), ('USD', 'USD')], max_length=10)),
                ('monto_moneda', models.DecimalField(decimal_places=6, max_digits=20)),
                ('monto_ars', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ref_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('applied_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('ref_movimiento', models.CharField(blank=True, max_length=64)),
                ('detalle', models.TextField(blank=True)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apuntes_exchange', to='usuarios.movimiento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('cuenta', 'Cuenta / Perfil'), ('operaciones', 'Operaciones (comprar/vender/swap)'), ('verificacion', 'Verificación KYC'), ('pagos', 'Depósitos / Retiros'), ('otro', 'Otro')], default='otro', max_length=32)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=16)),
                ('mensaje', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('estado', models.CharField(default='abierto', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
